apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
  labels:
    app: heart-disease-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      serviceAccountName: telemetry-ksa
      containers:
        - name: heart-disease-container
          image: us-central1-docker.pkg.dev/phonic-axle-473506-u8/heart-disease-repo/heart-disease-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: GCS_BUCKET
              value: "mlops_oppe2"
            - name: GCS_MODEL_BLOB
              value: "mlops_oppe2/models/model.pkl"
            - name: LOCAL_MODEL_PATH
              value: "models/model.pkl"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /ready_check
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /live_check
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2

